Integration with the telemetry package to create and push events
chef/chef-workstation pull request #2615
Opened 2022-02-24 20:04 UTC by nikhil2611

## Description
Integration with the telemetry package to create and push events

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

2022-03-28 13:27 UTC, sanghinitin requested changes

2022-03-28 13:27 UTC, sanghinitin commented on components/main-chef-wrapper/telemetry/telemetry.go
> +	uuid := fmt.Sprintf("%x-%x-%x-%x-%x",
create one func for creating format it will easy to change

2022-03-28 13:27 UTC, sanghinitin commented on components/main-chef-wrapper/telemetry/telemetry.go
> +		_, err := os.Create(telemetryInstallationIdentifierFile())
should return error

2022-03-28 16:18 UTC, nikhil2611 commented on components/main-chef-wrapper/telemetry/telemetry_test.go
> +	fmt.Println("got is------------", reflect.TypeOf(got))
done

2022-03-28 16:23 UTC, nikhil2611 commented on components/main-chef-wrapper/telemetry/telemetry.go
> +		_, err := os.Create(telemetryInstallationIdentifierFile())
Done

2022-12-14 05:38 UTC, vkarve-chef commented
closing old PRs. please reopen as needed.

2022-12-14 05:38 UTC, closed without merging